### PR TITLE
Add hightlight.js support to markdown renderer 

### PR DESCRIPTION
**Pull request by baseplate-admin**
Tracking : 
* https://github.com/markedjs/marked-highlight/issues/62
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65891

### CODE REVIEW

**Comment by baseplate-admin** [comment]
```html
&amp;lt;span &lt;span <span class="hljs-keyword">class</span>=<span class="hljs-string">&quot;hljs-keyword&quot;</span>&gt;<span class="hljs-keyword">class</span>&lt;<span class="hljs-regexp">/span&gt;=&lt;span class=&quot;hljs-string&quot;&gt;&amp;quot;hljs-variable language_&amp;quot;&lt;/</span>span&gt;&amp;gt;<span class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-variable language_&quot;</span>&gt;</span>console<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span></span>&amp;lt;<span class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-regexp&quot;</span>&gt;</span>/span<span class="hljs-symbol">&amp;gt;</span>.<span class="hljs-symbol">&amp;lt;</span>span class=<span class="hljs-symbol">&amp;quot;</span>hljs-title function_<span class="hljs-symbol">&amp;quot;</span><span class="hljs-symbol">&amp;gt;</span>log<span class="hljs-symbol">&amp;lt;</span>/<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span></span>span&amp;gt;(<span class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;language-xml&quot;</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-tag&quot;</span>&gt;</span><span class="hljs-symbol">&amp;lt;</span><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-name&quot;</span>&gt;</span>span<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span> <span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-attr&quot;</span>&gt;</span>class<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>=<span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-string&quot;</span>&gt;</span><span class="hljs-symbol">&amp;quot;</span>hljs-string<span class="hljs-symbol">&amp;quot;</span><span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span><span class="hljs-symbol">&amp;gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-symbol&quot;</span>&gt;</span><span class="hljs-symbol">&amp;amp;</span>#x27;<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>hello<span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-symbol&quot;</span>&gt;</span><span class="hljs-symbol">&amp;amp;</span>#x27;<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span><span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-tag&quot;</span>&gt;</span><span class="hljs-symbol">&amp;lt;</span>/<span class="hljs-tag">&lt;<span class="hljs-name">span</span> <span class="hljs-attr">class</span>=<span class="hljs-string">&quot;hljs-name&quot;</span>&gt;</span>span<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span><span class="hljs-symbol">&amp;gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span></span>)
```

We get this type of output

**Comment by baseplate-admin** [comment]
https://github.com/markedjs/marked-highlight/issues/62

**Comment by baseplate-admin** [comment]
@tokitou-san, If things are like this, then we need to return html from backend. Not a big fan of that  ( since it increases load on server )

**Comment by tokitou-san** [comment]
> @tokitou-san, If things are like this, then we need to return html from backend. Not a big fan of that ( since it increases load on server )

Okay, I didnt get it
This issue is still happening on code preview. like: type `const name = "Tokito";` in tripple back ticks and check the preview

**Comment by baseplate-admin** [comment]
Problem is with GC. The marked pollutes global namespace

**Comment by tokitou-san** [comment]
> Problem is with GC. The marked pollutes global namespace

Yea Okay, lets wait for their response on your issue

**Pull request merged**
