### PR TITLE
feat: 404 page add dynamic characters

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
image


Image doesn't align properly on mobile

**Comment by tokitou-san** [comment]
> Image doesn't align properly on mobile

Yes needa make responsive

**Comment by baseplate-admin** [comment]
I did some changes. Take a look

**Comment by baseplate-admin** [comment]
image

see i cant see the gradient

**Comment by tokitou-san** [comment]
> see i cant see the gradient

Its there, behind hair
needa do fix size lol

**Comment by baseplate-admin** [comment]
i think it's better to do the calculation using JS ?

**Comment by baseplate-admin** [comment]
@tokitou-san, use image loader?

**Comment by tokitou-san** [comment]
> i think it's better to do the calculation using JS ?

Okay? we can also avoid that way since we can do it manually.
Whatya think? wanna try js?

**Comment by baseplate-admin** [comment]
> wanna try js?

Last resort. Not a big fan of JS

**Comment by baseplate-admin** [comment]
I see layout shift

**Comment by baseplate-admin** [comment]
https://pagespeed.web.dev/analysis/https-core-project-v3-ui-git-add-more-fish-tokitou-san-vercel-app-mal-2/2ytu3ql61x?form_factor=desktop

Check this out

**Comment by baseplate-admin** [comment]
image


This is what is happening

**Comment by baseplate-admin** [comment]
image

good job

**Comment by tokitou-san** [comment]
@baseplate-admin Yo I'll add remaining fishes tommorrow...
and we needa find new fishes or we needa repair those cropped images
which one you feel better?

**Comment by baseplate-admin** [comment]
This is LGTM for now :)

Add more when you have time

**Pull request merged**
