### PR TITLE
feat: add structure for home page

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by tokitou-san** [comment]
@baseplate-admin Do we need to merge this now? Explore page needs a little bit of adjustments.

**Comment by baseplate-admin** [comment]
> @baseplate-admin Do we need to merge this now? Explore page needs a little bit of adjustments.

If we merge this we need a homepage to begin with :)

**Comment by tokitou-san** [comment]
> If we merge this we need a homepage to begin with :)

Well yea, we need to add homepage in this PR, right?
This gonna be a big boy :face_with_thermometer:

**Comment by baseplate-admin** [comment]
>  This gonna be a big boy 🤒

yea

**Pull request merged**
