### PR TITLE
Update to Svelte v4

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by baseplate-admin** [comment]
Tracking :

* https://github.com/pablo-abc/felte/issues/247

**Comment by baseplate-admin** [comment]
Build works locally

**Comment by tokitou-san** [comment]
> Build works locally

Okay, but still checkings and deployments failed :|

**Comment by baseplate-admin** [comment]
i can monkeypatch it. But it's better to wait

**Review by tokitou-san — APPROVED** [review]

**Pull request merged**
