### PR TITLE
feat: add input store to pass data

### PR DESCRIPTION
**Pull request by baseplate-admin**

### CODE REVIEW

**Comment by tokitou-san** [comment]
@baseplate-admin I think it would be better to use a custom combox instead using tippy like this.
What do you think?

**Comment by baseplate-admin** [comment]
> @baseplate-admin I think it would be better to use a custom combox instead using tippy like this.

I think it's better to use skeleton here. Cause Combobox is a bit harder to implement

**Comment by tokitou-san** [comment]
> I think it's better to use skeleton here. Cause Combobox is a bit harder to implement

Yes... Combobox from skeleton popup.
https://www.skeleton.dev/utilities/popups#combobox

**Comment by baseplate-admin** [comment]
Do we need this anymore?

**Comment by tokitou-san** [comment]
> Do we need this anymore?

No?
*Closing this

**Pull request closed without merging**
